### ISSUE TITLE
Simplify CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [emg888/prj-rev-bwfs-dasmoto#8]
It is a good idea to try and simplify the CSS code as much as you can to make the code cleaner and to remove repetitive code. There are several selectors that share properties like the font-family property, which you might simplify like so

```css
h1, h2, h3, p {
  font-family: Helvetica;
}
```
